[package]
name = "prepare-calldata-for-withdrawal"
version.workspace = true
homepage.workspace = true
license.workspace = true 
edition.workspace = true
authors.workspace = true

[dependencies]
sqlx = { workspace = true, features = ["postgres", "runtime-tokio-rustls"] }
tokio = { workspace = true, features = ["full"] }
client = { workspace = true }
storage = { workspace = true }
bincode = { workspace = true }
hex = { workspace = true }
ethers = { workspace = true }
clap = { workspace = true, features = ["derive"] }
