[graph]
targets = []
all-features = false
no-default-features = false

[output]
feature-depth = 1

[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "warn"
ignore = [
    "RUSTSEC-2024-0384", # instant is unmaintained
    "RUSTSEC-2024-0421", # idna accepts Punycode labels that do not produce any non-ASCII when decoded
    "RUSTSEC-2025-0009", # ring - Some AES functions may panic when overflow checking is enabled
    "RUSTSEC-2025-0010", # Versions of ring prior to 0.17 are unmaintained
    "RUSTSEC-2024-0436", # paste - no longer maintained
    "RUSTSEC-2025-0134", # rustls-pemfile is unmaintained
    "RUSTSEC-2025-0057", # fxhash - no longer maintained
    "RUSTSEC-2025-0056" # adler crate is unmaintained
]

[licenses]
version = 2
allow = [
    "MIT",
    "Apache-2.0",
    "ISC",
    "Unlicense",
    "MPL-2.0",
    "Unicode-DFS-2016",
    "CC0-1.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "OpenSSL",
]
confidence-threshold = 0.8
exceptions = []

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[licenses.private]
ignore = false
registries = []

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = [""]
gitlab = [""]
bitbucket = [""]
