eth_client_ws_url = "wss://goerli.infura.io/ws/v3/1f737de7e38a4f1c8c37437ada7a08d8"
l1_erc20_bridge_proxy_addr = "0x927DdFcc55164a59E0F33918D13a2D559bC10ce7"
l2_erc20_bridge_addr = "0x00ff932A6d70E2B8f1Eb4919e1e09C1923E7e57b"
diamond_proxy_addr = "0x1908e2BF4a88F91E4eF0DC72f02b8Ea36BEa2319"
api_web3_json_rpc_ws_url = "wss://testnet.era.zksync.dev/ws"
database_url = "postgres://postgres@localhost/finalizer_local"
start_from_l2_block = 7000000
