[package]
name = "delete-finalization-data-migration"
version.workspace = true
homepage.workspace = true
license.workspace = true 
edition.workspace = true
authors.workspace = true

[dependencies]
color-eyre = { workspace = true }
eyre = { workspace = true } 
sqlx = { workspace = true, features = ["postgres", "runtime-tokio-rustls"] }
tokio = { workspace = true, features = ["full"] }
storage = { workspace = true }
dotenvy = { workspace = true }
