[package]
name = "withdrawals-meterer"
version = "0.1.11"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
ethers = "2.0.10"
lazy_static = "1.4.0"
metrics = "0.21.1"
thiserror = "1.0.49"
tokio = "1.32.0"

client = { path = "../client" }
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio-rustls"] }
storage = { path = "../storage" }
vlog = { path = "../vlog" }
