name: Cargo Deny

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo_deny:
    runs-on: [matterlabs-ci-runner]
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources

    # Prevent sudden announcement of a new advisory from failing ci:
    continue-on-error: ${{ matrix.checks == 'advisories' }}

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check ${{ matrix.checks }}
