name: Check Spelling

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

env: 
  CARGO_TERM_COLOR: always

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Install cargo-spellcheck
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-spellcheck
          
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Run cargo-spellcheck
        run: cargo spellcheck --cfg=.github/spellcheck/finalizer.cfg --code 1
