name: CI

on:
  push:
    branches:
      - main

  pull_request:
  merge_group:

env: 
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      
      - name: Build project
        run: |
          cargo build

      - name: Run clippy
        run: |
          cargo clippy -- -D warnings -W clippy::unused_async

      - name: Check formatting
        run: |
          cargo fmt --check

      - name: Run Tests
        run: |
          cargo test --all
