name: CI

on:
  push:
    branches:
      - main

  pull_request:

env: 
  CARGO_TERM_COLOR: always
  DATABASE_URL: 'postgres://postgres@localhost/finalizer_local'


concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    runs-on: [self-hosted, ci-runner]

    steps:
      - uses: actions/checkout@v2

      - name: Start services
        run: |
          docker-compose -f docker-compose-runner.yml pull
          docker-compose -f docker-compose-runner.yml up --build -d postgres

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install sqlx
        run: |
          cargo install sqlx-cli --no-default-features --features rustls,postgres

      - name: Init DB
        run: |
          cd ./storage/
          sqlx database create
          sqlx migrate run
          cd ../

      - name: Build project
        run: |
          cargo build

      - name: Run clippy
        run: |
          cargo clippy -- -D warnings

      - name: Check formatting
        run: |
          cargo fmt --check
